### ISSUE TITLE
Getting error with `rake db:create`

### ISSUE THREAD

**Issue by pikender** [vinsol/shopspree-sales-app#57]
*It should be replicable on existing codebase with no changes and just `bundle install` and `bundle exec rake db:create` . Check the trace at end of the description*

**Here are the steps which led to the issue just in case above is working without any issues 😊**

I have updated Gemfile to be compatible with latest Rails v4.2.7.1 and latest spree with branch 3-0-stable

**P.S.** All the gems with `path: option` are pointing to same branch as defined in Gemfile

**Here is my Gemfile and Git Diff of changes**

```ruby
source 'https://rubygems.org'

gem 'rails',                                  '4.2.7.1'
gem 'mysql2',                                 '~> 0.3.18'
gem 'jquery-rails',                           '~> 4.0'
gem 'jquery-ui-rails',                        '~> 5.0.3'
gem 'paperclip',                              '~> 4.2'
gem 'chewy',                                  '~> 0.8.3'
#gem 'spree',                                  github: 'spree/spree',                        branch: '3-0-stable'
#gem 'spree_gateway',                          github: 'spree/spree_gateway',                branch: '3-0-stable'
#gem 'spree_auth_devise',                      github: 'spree/spree_auth_devise',            branch: '3-0-stable'
gem 'spree', path: '~/spree/spree'
gem 'spree_gateway', path: '~/spree/spree_gateway'
gem 'spree_auth_devise', path: '~/spree/spree_auth_devise'
gem 'spree_mail_settings',                    github: 'spree-contrib/spree_mail_settings',  branch: '3-0-stable'
gem 'spree_ams', path: '~/spree/spree_ams'
#gem 'spree_ams',                              github: 'hhff/spree_ams',                     branch: '3-0-alpha'
gem 'spree_reviews',                          github: 'spree-contrib/spree_reviews',        branch: '3-0-stable'
#gem 'spree_address_book',                     github: 'spree-contrib/spree_address_book',   branch: '3-0-stable'
gem 'spree_address_book', path: '~/spree/spree_address_book'
gem 'aws-sdk',                                '< 2.0'
gem 'spree_wishlist',                         github: 'spree-contrib/spree_wishlist',         branch: '3-0-stable'
#gem 'spree_email_to_friend',                  github: 'spree-contrib/spree_email_to_friend',  branch: '3-0-stable'
gem 'spree_email_to_friend', path: '~/spree/spree_email_to_friend'

group :assets do
  gem 'therubyracer',                         '~> 0.12.1', platforms: :ruby
  gem 'uglifier',                             '~> 2.7'
  gem 'sass-rails',                           '~> 5.0'
  gem 'coffee-rails',                         '~> 4.1.0'
end

group :production do
  gem 'rails_12factor',                       '~> 0.0.3'
  gem 'pg',                                   '~> 0.18.3'
end

group :development, :test do
  gem 'byebug',                               '~> 5.0.0'
  gem 'web-console',                          '~> 2.0'
  gem 'quiet_assets',                         '~> 1.1.0'
end

group :development do
  gem 'capistrano',                           '~> 3.2.1'
  gem 'capistrano-bundler',                   '~> 1.1.4'
  gem 'capistrano-rails',                     '~> 1.1.3'
  gem 'binding_of_caller',                    '~> 0.7.2'
  gem 'better_errors',                        '~> 2.0.0'
  gem 'bullet',                               '~> 4.14.7'
end

group :test do
  gem 'rspec-rails',                          '~> 3.1.0'
  gem 'rspec-activemodel-mocks',              '~> 1.0.1'
  gem 'factory_girl_rails',                   '~> 4.4.1'
  gem 'shoulda-matchers',                     '~> 2.8.0', require: false
  gem 'shoulda-callback-matchers',            '~> 1.1.3'
  gem 'simplecov',                            '~> 0.9.2', require: false
end
```

```diff
diff --git a/Gemfile b/Gemfile
index 1514346..c6627f2 100644
--- a/Gemfile
+++ b/Gemfile
@@ -1,21 +1,27 @@
 source 'https://rubygems.org'
 
-gem 'rails',                                  '4.2.4'
+gem 'rails',                                  '4.2.7.1'
 gem 'mysql2',                                 '~> 0.3.18'
-gem 'jquery-rails',                           '~> 4.0.3'
+gem 'jquery-rails',                           '~> 4.0'
 gem 'jquery-ui-rails',                        '~> 5.0.3'
-gem 'paperclip',                              '~> 4.2.4'
+gem 'paperclip',                              '~> 4.2'
 gem 'chewy',                                  '~> 0.8.3'
-gem 'spree',                                  github: 'spree/spree',                        branch: '3-0-stable'
-gem 'spree_gateway',                          github: 'spree/spree_gateway',                branch: '3-0-stable'
-gem 'spree_auth_devise',                      github: 'spree/spree_auth_devise',            branch: '3-0-stable'
+#gem 'spree',                                  github: 'spree/spree',                        branch: '3-0-stable'
+#gem 'spree_gateway',                          github: 'spree/spree_gateway',                branch: '3-0-stable'
+#gem 'spree_auth_devise',                      github: 'spree/spree_auth_devise',            branch: '3-0-stable'
+gem 'spree', path: '~/spree/spree'
+gem 'spree_gateway', path: '~/spree/spree_gateway'
+gem 'spree_auth_devise', path: '~/spree/spree_auth_devise'
 gem 'spree_mail_settings',                    github: 'spree-contrib/spree_mail_settings',  branch: '3-0-stable'
-gem 'spree_ams',                              github: 'hhff/spree_ams',                     branch: '3-0-alpha'
+gem 'spree_ams', path: '~/spree/spree_ams'
+#gem 'spree_ams',                              github: 'hhff/spree_ams',                     branch: '3-0-alpha'
 gem 'spree_reviews',                          github: 'spree-contrib/spree_reviews',        branch: '3-0-stable'
-gem 'spree_address_book',                     github: 'spree-contrib/spree_address_book',   branch: '3-0-stable'
+#gem 'spree_address_book',                     github: 'spree-contrib/spree_address_book',   branch: '3-0-stable'
+gem 'spree_address_book', path: '~/spree/spree_address_book'
 gem 'aws-sdk',                                '< 2.0'
 gem 'spree_wishlist',                         github: 'spree-contrib/spree_wishlist',         branch: '3-0-stable'
-gem 'spree_email_to_friend',                  github: 'spree-contrib/spree_email_to_friend',  branch: '3-0-stable'
+#gem 'spree_email_to_friend',                  github: 'spree-contrib/spree_email_to_friend',  branch: '3-0-stable'
+gem 'spree_email_to_friend', path: '~/spree/spree_email_to_friend'
```

**Here are some of the git repos downloaded locally and changes in them**

*spree_address_book*

```diff
pikender@Pikenders-MacBook-Pro:~/spree/spree_address_book$ git diff
diff --git a/spree_address_book.gemspec b/spree_address_book.gemspec
index ed30e6e..69e39d2 100644
--- a/spree_address_book.gemspec
+++ b/spree_address_book.gemspec
@@ -14,7 +14,7 @@ Gem::Specification.new do |s|
   s.require_path = 'lib'
   s.requirements << 'none'
 
-  s.add_dependency 'spree_core', '~> 3.0.0.rc'
+  s.add_dependency 'spree_core', '~> 3.0.0'
   s.add_dependency 'spree_auth_devise'
 
   s.add_development_dependency 'rspec-rails', '~> 3.4.1'
```

*spree_email_to_friend*

```diff
pikender@Pikenders-MacBook-Pro:~/spree/spree_email_to_friend$ git diff
diff --git a/spree_email_to_friend.gemspec b/spree_email_to_friend.gemspec
index dcf6b70..eae1b77 100755
--- a/spree_email_to_friend.gemspec
+++ b/spree_email_to_friend.gemspec
@@ -23,7 +23,7 @@ Gem::Specification.new do |s|
 
   s.has_rdoc = false
 
-  s.add_dependency 'spree_core', '~> 3.0.0.rc2'
+  s.add_dependency 'spree_core', '~> 3.0.0'
   s.add_dependency 'recaptcha', '>= 0.3.1'
 
   s.add_development_dependency 'rspec-rails', '~> 3.2.0'
```

**Run `bundle update`**

**Run `bundle exec rake db:create`**

- Ensure config/database.yml is set properly
- Getting exception

```sh
pikender@Pikenders-MacBook-Pro:~/rails5/shopspree-sales-app$ bundle exec rake db:create
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x007ff8e5102ad0>
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/gems/rspec-core-3.1.7/lib/rspec/core/rake_task.rb:104:in `define'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/gems/rspec-core-3.1.7/lib/rspec/core/rake_task.rb:80:in `initialize'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/gems/rspec_api_documentation-4.9.0/lib/tasks/docs.rake:4:in `new'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/gems/rspec_api_documentation-4.9.0/lib/tasks/docs.rake:4:in `<top (required)>'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/gems/rspec_api_documentation-4.9.0/lib/rspec_api_documentation/railtie.rb:4:in `block in <class:Railtie>'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/gems/railties-4.2.7.1/lib/rails/railtie.rb:237:in `instance_exec'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/gems/railties-4.2.7.1/lib/rails/railtie.rb:237:in `block in run_tasks_blocks'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/gems/railties-4.2.7.1/lib/rails/railtie.rb:245:in `each'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/gems/railties-4.2.7.1/lib/rails/railtie.rb:245:in `each_registered_block'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/gems/railties-4.2.7.1/lib/rails/railtie.rb:237:in `run_tasks_blocks'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/gems/railties-4.2.7.1/lib/rails/application.rb:451:in `block in run_tasks_blocks'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/gems/railties-4.2.7.1/lib/rails/engine/railties.rb:13:in `each'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/gems/railties-4.2.7.1/lib/rails/engine/railties.rb:13:in `each'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/gems/railties-4.2.7.1/lib/rails/application.rb:451:in `run_tasks_blocks'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/gems/railties-4.2.7.1/lib/rails/engine.rb:453:in `load_tasks'
/Users/pikender/rails5/shopspree-sales-app/Rakefile:6:in `<top (required)>'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/bin/ruby_executable_hooks:15:in `eval'
/Users/pikender/.rvm/gems/ruby-2.3.1@spree/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

**Comment by pikender** [comment]
Oops .. just got to know that its rake specific and not application specific 😞 

[This](http://stackoverflow.com/questions/35893584/nomethoderror-undefined-method-last-comment-after-upgrading-to-rake-11) solved it. Closing to not bother 👍
