### ISSUE TITLE
Errors after basic configuration

### ISSUE THREAD

**Issue by kaustubhkabra** [vinsol/shopspree-sales-app#58]
Ruby - ruby 2.3.0
Rails -  4.2.4
I was able to get API working by installing https://github.com/vinsol-spree-contrib/shopspree-sales-app. I am able to hit documentation URL and documentation page shows up.
<img width="1399" alt="documentation" src="https://cloud.githubusercontent.com/assets/642690/22362254/521822ba-e487-11e6-8ab2-b398483bcabd.png">
However, GET api/ams/home got hit once and then it gave this error.
<img width="517" alt="home" src="https://cloud.githubusercontent.com/assets/642690/22362278/790355fc-e487-11e6-8e84-12b858b19756.png">
And, GET api/ams/products shows TCP connection error.
<img width="956" alt="products" src="https://cloud.githubusercontent.com/assets/642690/22362291/88fa1482-e487-11e6-9afd-6e1188d4d8e6.png">

Can someone help here on what is wrong ?

**Comment by ShubhamGupta** [comment]
You'll need to install and run `elasticsearch` server locally. By default it runs on port 9200.

For `/api/ams/home` please share the error backtrace.

**Comment by kaustubhkabra** [comment]
Yes, elasticsearch solved the issue for /api/ams/products. Here is the stack trace for GET api/ams/home - 
```
Started GET "/api/ams/home" for ::1 at 2017-01-27 12:30:00 +0530
DEBUG: Chewy strategies stack: [2] <- atomic @ /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/chewy-0.8.3/lib/chewy/railtie.rb:16
Processing by Spree::Api::Ams::HomeController#show as HTML
  Spree::User Load (0.3ms)  SELECT  `spree_users`.* FROM `spree_users` WHERE `spree_users`.`deleted_at` IS NULL AND `spree_users`.`spree_api_key` = '' LIMIT 1
  Spree::SalesAppConfiguration Load (0.2ms)  SELECT  `spree_sales_app_configurations`.* FROM `spree_sales_app_configurations`  ORDER BY `spree_sales_app_configurations`.`id` ASC LIMIT 1
  Spree::Taxon Load (0.2ms)  SELECT  `spree_taxons`.* FROM `spree_taxons`  ORDER BY `spree_taxons`.`updated_at` DESC LIMIT 1
  CACHE (0.0ms)  SELECT  `spree_sales_app_configurations`.* FROM `spree_sales_app_configurations`  ORDER BY `spree_sales_app_configurations`.`id` ASC LIMIT 1
  CACHE (0.0ms)  SELECT  `spree_taxons`.* FROM `spree_taxons`  ORDER BY `spree_taxons`.`updated_at` DESC LIMIT 1
undefined method `updated_at' for nil:NilClass
/Users/kaustubh/Desktop/Workspace/Samples/shopspree-sales-app/app/models/spree/sales_app_configuration.rb:7:in `get_latest_config'
/Users/kaustubh/Desktop/Workspace/Samples/shopspree-sales-app/app/serializers/spree/home_serializer.rb:9:in `checksum'
(eval):3:in `_fast_attributes'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/active_model_serializers-0.8.3/lib/active_model/serializer.rb:467:in `rescue in attributes'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/active_model_serializers-0.8.3/lib/active_model/serializer.rb:455:in `attributes'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/active_model_serializers-0.8.3/lib/active_model/serializer.rb:479:in `_serializable_hash'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/active_model_serializers-0.8.3/lib/active_model/serializer.rb:361:in `serializable_hash'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/active_model_serializers-0.8.3/lib/active_model/serializer.rb:349:in `as_json'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/json/encoding.rb:35:in `encode'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/json/encoding.rb:22:in `encode'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/active_model_serializers-0.8.3/lib/active_model/serializer.rb:333:in `to_json'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/renderers.rb:116:in `block in <module:Renderers>'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/active_model_serializers-0.8.3/lib/action_controller/serialization.rb:48:in `block (2 levels) in <module:Serialization>'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/renderers.rb:45:in `block in _render_to_body_with_renderer'
/Users/kaustubh/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/set.rb:306:in `each_key'
/Users/kaustubh/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/set.rb:306:in `each'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/renderers.rb:41:in `_render_to_body_with_renderer'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/abstract_controller/rendering.rb:25:in `render'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/rendering.rb:16:in `render'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/kaustubh/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:43:in `render'
/Users/kaustubh/Desktop/Workspace/Samples/shopspree-sales-app/app/controllers/spree/api/ams/home_controller.rb:11:in `show'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:198:in `process_action'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/rendering.rb:10:in `process_action'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/rescue.rb:29:in `process_action'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:137:in `process'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionview-4.2.4/lib/action_view/rendering.rb:30:in `process'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal.rb:196:in `dispatch'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal.rb:237:in `block in action'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:45:in `serve'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `each'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `serve'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:821:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/engine.rb:518:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/railtie.rb:194:in `public_send'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/railtie.rb:194:in `method_missing'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:51:in `serve'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `each'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `serve'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:821:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/bullet-4.14.7/lib/bullet/rack.rb:10:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/flash.rb:260:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/query_cache.rb:36:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:377:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/reloader.rb:73:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/better_errors-2.0.0/lib/better_errors/middleware.rb:84:in `protected_app_call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/better_errors-2.0.0/lib/better_errors/middleware.rb:79:in `better_errors_call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/better_errors-2.0.0/lib/better_errors/middleware.rb:57:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/web-console-2.2.1/lib/web_console/middleware.rb:39:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/chewy-0.8.3/lib/chewy/railtie.rb:16:in `block in call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/chewy-0.8.3/lib/chewy/strategy.rb:60:in `wrap'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/chewy-0.8.3/lib/chewy.rb:173:in `strategy'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/chewy-0.8.3/lib/chewy/railtie.rb:16:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:38:in `call_app'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `block in call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `tagged'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/quiet_assets-1.1.0/lib/quiet_assets.rb:27:in `call_with_quiet_assets'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/static.rb:116:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/engine.rb:518:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.4/lib/rails/application.rb:165:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
/Users/kaustubh/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/Users/kaustubh/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/Users/kaustubh/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
  Rendered text template (0.0ms)
Completed 422 Unprocessable Entity in 17ms (Views: 7.8ms | ActiveRecord: 1.1ms)
DEBUG: Chewy strategies stack: [2] -> atomic @ /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/chewy-0.8.3/lib/chewy/railtie.rb:16

```

**Comment by kaustubhkabra** [comment]
This might/might not be related but **bundle exec rake spree_sample:load** has this stack trace -

```
Kaustubhs-MacBook-Pro:shopspree-sales-app kaustubh$ bundle exec rake spree_sample:load
[WARNING] You are not setting Devise.secret_key within your application!
You must set this in config/initializers/devise.rb. Here's an example:
 
Devise.secret_key = "1979a2912284f819f4726d190c8eafd5550822119f04116d09840579e8428cd7510a21f39eb800a2ae7f10ab791c847884d2"
Loaded Payment Methods samples
Loaded Shipping Categories samples
Loaded Shipping Methods samples
Loaded Tax Categories samples
Loaded Tax Rates samples
rake aborted!
Chewy::UndefinedUpdateStrategy: Index update strategy is undefined in current context.
Please wrap your code with `Chewy.strategy(:strategy_name) block.`
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/chewy-0.8.3/lib/chewy/strategy/base.rb:17:in `update'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/chewy-0.8.3/lib/chewy/type/observe.rb:70:in `update_index'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/chewy-0.8.3/lib/chewy/type/observe.rb:28:in `block in update_proc'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:446:in `instance_exec'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:263:in `block in simple'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:506:in `block in call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:506:in `each'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:506:in `call'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_commit_callbacks'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:314:in `committed!'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:89:in `commit_records'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:153:in `commit'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:175:in `commit_transaction'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `within_new_transaction'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:291:in `save!'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/persistence.rb:51:in `create!'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/bundler/gems/spree-a275c9db4f0c/sample/db/samples/products.rb:129:in `block in <top (required)>'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/bundler/gems/spree-a275c9db4f0c/sample/db/samples/products.rb:124:in `each'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/bundler/gems/spree-a275c9db4f0c/sample/db/samples/products.rb:124:in `<top (required)>'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/bundler/gems/spree-a275c9db4f0c/sample/lib/spree/sample.rb:13:in `load_sample'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/bundler/gems/spree-a275c9db4f0c/sample/lib/spree_sample.rb:16:in `load_samples'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/bundler/gems/spree-a275c9db4f0c/sample/lib/tasks/sample.rake:20:in `block (2 levels) in <top (required)>'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:74:in `load'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:27:in `run'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.3/lib/bundler/cli.rb:335:in `exec'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.3/lib/bundler/cli.rb:20:in `dispatch'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.3/lib/bundler/cli.rb:11:in `start'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.3/exe/bundle:32:in `block in <top (required)>'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.3/exe/bundle:24:in `<top (required)>'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/bin/bundle:22:in `load'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/bin/bundle:22:in `<main>'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/kaustubh/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => spree_sample:load
(See full trace by running task with --trace)
```

**Comment by kaustubhkabra** [comment]
Though elasticsearch solved the localhost 9002 connectivity issue, hitting GET api/ams/products returns this consistent response now -
`{"exception":"[404] {\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"spree\",\"index_uuid\":\"_na_\",\"index\":\"spree\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"spree\",\"index_uuid\":\"_na_\",\"index\":\"spree\"},\"status\":404}"}`

**Comment by ShubhamGupta** [comment]
The error trace states clearly `index_not_found_exception`. Please read the documentation of gem `chewy` to set it up properly. You'll need to create the indices.

https://github.com/toptal/chewy.

Specifically, have a look at the rake tasks that the gem offers.

**Comment by kaustubhkabra** [comment]
Ok thanks, **bundle exec rake spree_sample:load** stack trace (pasted above) also points to similar issue. Are they both related to chewy ? Could it be because of a specific version installed ?

**Comment by shitaljaju** [comment]
Hi @kaustubh-kabra, did you find a solution to this ? I am stuck at exact same problem. I am using Ubuntu, ruby 2.3.0 and rails 4.2.4.
@ShubhamGupta @bansalakhil  Please help in giving a sample solution to this.

**Comment by kaustubhkabra** [comment]
@shitaljaju Not yet. Since I am a newbie to RoR, trying to get a direction. @ShubhamGupta Any sample would be really helpful !

**Comment by ShubhamGupta** [comment]
@kaustubh-kabra @shitaljaju I'll be looking into this issue. It seems to stem from recent Elasticsearch version. Please tell me the Elasticsearch version you are using.

**Comment by kaustubhkabra** [comment]
Had to make configuration changes and issue is resolved.
