### ISSUE TITLE
I get chewy error issue on  "bundle exec rake spree_sample:load"

### ISSUE THREAD

**Issue by manishkongari** [vinsol/shopspree-sales-app#61]
Kindly checkout this link

http://stackoverflow.com/questions/41295387/vinsol-spree-contrib-shopspree-sales-app-installation-error

asdf08:~/workspace (master) $ bundle exec rake spree_sample:load
Loaded Payment Methods samples
Loaded Shipping Categories samples
Loaded Shipping Methods samples
Loaded Tax Categories samples
Loaded Tax Rates samples
rake aborted!
Chewy::UndefinedUpdateStrategy: Index update strategy is undefined in current context.
Please wrap your code with `Chewy.strategy(:strategy_name) block.`
/usr/local/rvm/gems/ruby-2.3.0/gems/chewy-0.8.3/lib/chewy/strategy/base.rb:17:in `update'
/usr/local/rvm/gems/ruby-2.3.0/gems/chewy-0.8.3/lib/chewy/type/observe.rb:70:in `update_index'
/usr/local/rvm/gems/ruby-2.3.0/gems/chewy-0.8.3/lib/chewy/type/observe.rb:28:in `block in update_proc'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:446:in `instance_exec'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:263:in `block in simple'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:506:in `block in call'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:506:in `each'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:506:in `call'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_commit_callbacks'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:314:in `committed!'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:89:in `commit_records'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:153:in `commit'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:175:in `commit_transaction'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `within_new_transaction'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:291:in `save!'
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-4.2.4/lib/active_record/persistence.rb:51:in `create!'
/usr/local/rvm/gems/ruby-2.3.0/bundler/gems/spree-a275c9db4f0c/sample/db/samples/products.rb:129:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/bundler/gems/spree-a275c9db4f0c/sample/db/samples/products.rb:124:in `each'
/usr/local/rvm/gems/ruby-2.3.0/bundler/gems/spree-a275c9db4f0c/sample/db/samples/products.rb:124:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.3.0/bundler/gems/spree-a275c9db4f0c/sample/lib/spree/sample.rb:13:in `load_sample'
/usr/local/rvm/gems/ruby-2.3.0/bundler/gems/spree-a275c9db4f0c/sample/lib/spree_sample.rb:16:in `load_samples'
/usr/local/rvm/gems/ruby-2.3.0/bundler/gems/spree-a275c9db4f0c/sample/lib/tasks/sample.rake:20:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/bin/bundle:23:in `load'
/usr/local/rvm/gems/ruby-2.3.0/bin/bundle:23:in `<main>'
/usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => spree_sample:load
(See full trace by running task with --trace)

**Comment by manishkongari** [comment]
Is the code upto date ?

**Comment by infosandhy** [comment]
i got same error like this... how to resolve?

thank you
